### ISSUE TITLE
Error with "az_ngw_ids" output when nat gateway is disabled

### ISSUE THREAD

**Issue by PiWhy** [cloudposse/terraform-aws-multi-az-subnets#2]
I have got the following error when trying to create only public subnets with no NAT gateways : 

> Error: Error refreshing state: 1 error(s) occurred:
> 
> * module.public_subnets.output.az_ngw_ids: zipmap: count of keys (3) does not match count of values (0) in:
> 
> ${zipmap(var.availability_zones, matchkeys(aws_nat_gateway.public.*.id, aws_nat_gateway.public.*.tags.AZ, var.availability_zones))}

There is a mismatch with zipmap because there are (here) 3 availability zones and matchkeys returns an empty list.

Here is my config :
```
data "aws_availability_zones" "az" {}

module "vpc" {
    source     = "git::https://github.com/cloudposse/terraform-aws-vpc.git?ref=master"
    namespace  = "${local.prefix}"
    name       = "vpc"
    stage      = "${var.environment}"
    cidr_block = "172.30.0.0/16"
}

module "public_subnets" {
    source              = "git::https://github.com/cloudposse/terraform-aws-multi-az-subnets.git?ref=master"
    namespace           = "${local.prefix}"
    stage               = "${var.environment}"
    name                = "${local.project}"
    availability_zones  = "${data.aws_availability_zones.az.names}"
    vpc_id              = "${module.vpc.vpc_id}"
    cidr_block          = "${module.vpc.vpc_cidr_block}"
    type                = "public"
    igw_id              = "${module.vpc.igw_id}"
    nat_gateway_enabled = "false"
}
```

Of course, if I comment out the az_ngw_ids output, everything is fine but it doesn't seem like a long term solution. I'm quite new to Terraform's syntax. Do you think about a workaround or a fix for this issue ?

Thanks

**Comment by aknysh** [comment]
@PiWhy 
It's probably because of the new version of Terraform you are using.
the module was tested some time ago, but they changed a lot in Terraform recently.
we are looking into that and will let you know ASAP.
thanks for testing!

**Comment by aknysh** [comment]
@PiWhy 
we fixed the issue and merged to master and tagged a new release
https://github.com/cloudposse/terraform-aws-multi-az-subnets/releases/tag/0.1.1

let us know if it's working for you.
will close the issue for now.
thanks again for testing!

**Comment by PiWhy** [comment]
@aknysh 
That was fast !

Thank you so much.
