### ISSUE TITLE
Q: is it possible to associate all subnetworks with the main routing table?

### ISSUE THREAD

**Issue by vitalykarasik** [cloudposse/terraform-aws-multi-az-subnets#59]
This module creates a route table for each subnetwork. Is it possible to avoid that and create just one route table for all subnetworks?

**Comment by Nuru** [comment]
This module does not currently support a single route table for all subnets. [terraform-aws-dynamic-subnets](https://github.com/cloudposse/terraform-aws-dynamic-subnets) does that by default for "public" subnets. Generally, private subnets want to have a route to a NAT Gateway in their own availability zone, so it is uncommon to want them to share a route table.
